config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index', as: 'home'
  get 'registrations/new', as: 'sign_up'
  get 'sessions/new', as: 'sign_in'

  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webovka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-bold"><%= link_to 'Webová Aplikace', home_path %></h5>
    <nav class="my-2 my-md-0 mr-md-3">

      <span class="p-1 text-dark"><%= link_to 'Registrace', sign_up_path %></span>
      <span class="p-1 text-dark"><%= link_to 'Přihlášení', sign_in_path %></span>
    </nav>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">
    <%= yield %>
  </div>



  </body>
</html>

app/views/welcome/index.html.erb
<div class="container text-center text-capitalize" >
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>  <br>  <br>  <br>  <br>
  <h1 class="text-capitalize">VÍTÁME VÁS NA PORTÁLU!</h1>

</div>